export const ADD_PUBLICATION = "ADD_PUBLICATION";
export const REMOVE_PUBLICATION = "REMOVE_PUBLICATION";

export const FETCH_PUBLICATIONS_REQUEST = 'FETCH_PUBLICATIONS_REQUEST';
export const FETCH_PUBLICATIONS_SUCCESS = 'FETCH_PUBLICATIONS_SUCCESS';
export const FETCH_PUBLICATIONS_FAILURE = 'FETCH_PUBLICATIONS_FAILURE';

export const FETCH_PUBLICATION_REQUEST = 'FETCH_PUBLICATION_REQUEST';
export const FETCH_PUBLICATION_SUCCESS = 'FETCH_PUBLICATION_SUCCESS';
export const FETCH_PUBLICATION_FAILURE = 'FETCH_PUBLICATION_FAILURE';

export const POST_PUBLICATION_REQUEST = 'POST_PUBLICATION_REQUEST';
export const POST_PUBLICATION_SUCCESS = 'POST_PUBLICATION_SUCCESS';
export const POST_PUBLICATION_FAILURE = 'POST_PUBLICATION_FAILURE';
